image:
  name: atlassian/default-image:2

options:
  docker: true

definitions:
  services:
    dockerc:
      image: docker/compose:1.25.4
  # generic re-usable steps
  steps:
    - step: # use a multiline step to set environment variables
        script: &setenv |
          export IMAGE_NAME=docker.io/ternau/landscapes.cosmoz.rest.api
          export IMAGE_TAG=$(git describe)

    - step: &build-test-step
        script:
          - *setenv
          # build latest
          - cd contrib/docker
          - docker-compose -f docker-compose.build.yml build --build-arg CLONE_ORIGIN=$BITBUCKET_GIT_HTTP_ORIGIN --build-arg CLONE_COMMIT=$BITBUCKET_COMMIT --build-arg CLONE_BRANCH=$BITBUCKET_BRANCH
          - cd ../..
        services:
          - dockerc

pipelines:
  branches:
    develop:
      - step: *build-test-step
    master:
      - step: *build-test-step
    publish:
      - step:
          script:
            - *setenv
            - cd contrib/docker
            - docker-compose -f docker-compose.build.yml build --build-arg CLONE_ORIGIN=$BITBUCKET_GIT_HTTP_ORIGIN --build-arg CLONE_COMMIT=$BITBUCKET_COMMIT --build-arg CLONE_BRANCH=$BITBUCKET_BRANCH
            - docker tag $IMAGE_NAME $IMAGE_NAME:$IMAGE_TAG
            - docker tag $IMAGE_NAME $IMAGE_NAME:latest
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker push $IMAGE_NAME
            - docker push $IMAGE_NAME:$IMAGE_TAG
            - docker push $IMAGE_NAME:latest
          services:
            - dockerc

  pull-requests:
    "**":
      - step: *build-test-step
