# -*- coding: utf-8 -*-
#
import sys
from util import load_env
from os import getenv
load_env()
module = sys.modules[__name__]
TRUTHS = {True, 1, '1', 'T', 't', 'true', 'TRUE', 'True'}
CONFIG = module.CONFIG = {}

OVERRIDE_SERVER_NAME = CONFIG['OVERRIDE_SERVER_NAME'] = getenv("SANIC_OVERRIDE_SERVER_NAME", "localhost:9001")
PROXY_ROUTE_BASE = CONFIG['PROXY_ROUTE_BASE'] = getenv("SANIC_PROXY_ROUTE_BASE", "")
SANIC_SERVER_NAME = CONFIG['SANIC_SERVER_NAME'] = getenv("SANIC_SERVER_NAME", "")
INFLUXDB_HOST = CONFIG['INFLUXDB_HOST'] = getenv("INFLUX_DB_HOST", "cosmoz.influxdb")
INFLUXDB_PORT = CONFIG['INFLUXDB_PORT'] = int(getenv("INFLUX_DB_PORT", 8086))
INFLUXDB_USERNAME = CONFIG['INFLUXDB_USERNAME'] = getenv("INFLUX_DB_USERNAME", None)
INFLUXDB_PASSWORD = CONFIG['INFLUXDB_PASSWORD'] = getenv("INFLUX_DB_PASSWORD", None)
INFLUXDB_NAME = CONFIG['INFLUXDB_NAME'] = getenv("INFLUX_DB_NAME", "cosmoz")
MONGODB_HOST = CONFIG['MONGODB_HOST'] = getenv("MONGO_DB_HOST", "cosmoz.mongodb")
MONGODB_PORT = CONFIG['MONGODB_PORT'] = int(getenv("MONGO_DB_PORT", 27017))
MONGODB_NAME = CONFIG['MONGODB_NAME'] = getenv("MONGO_DB_NAME", "cosmoz")
METRICS_DIRECTORY = CONFIG['METRICS_DIRECTORY'] = getenv("METRICS_DIRECTORY", ".")
DEBUG = CONFIG['DEBUG'] = getenv("SANIC_DEBUG", '') in TRUTHS
