version: "3.6"
# Requires docker-compose min version 1.22
# (for complex labels, and for $PWD in dockerfile:)
services:

  landscapes.cosmoz.rest.api:
    image: docker.io/ternau/landscapes.cosmoz.rest.api:latest
    build:
      dockerfile: "${PWD}/Dockerfiles/restapi.Dockerfile"
      context: ../../
    hostname: "landscapes.cosmoz.rest.api"
    environment:
      - PYTHONUNBUFFERED=TRUE
